export default{
  icProfile: require('../assets/Images/bi_person-circle.png'),
  icHome: require('../assets/Images/Vector.png'),
  icNotifications: require('../assets/Images/ri_notification-4-line.png'),
  dreptunghi1: require('../assets/Images/Rectangle13.png'),
  dreptunghi1: require('../assets/Images/Rectangle12.png'),
  presenting: require('../assets/Images/image14.png'),
  presenting2: require('../assets/Images/image15.png'),
  logo1: require('../assets/Images/image4.png'),
  location: require('../assets/Images/locationicon2.png'),
  logo2: require('../assets/Images/logo2.png'),
  rectangle1: require('../assets/Images/Rectangle1.png'),
  rectangle2: require('../assets/Images/Rectangle2.png'),
  rectangle3: require('../assets/Images/Rectangle3.png'),
}