export default{
  icProfile: require('../assets/Images/bi_person-circle.png'),
  icHome: require('../assets/Images/Vector.png'),
  icNotifications: require('../assets/Images/ri_notification-4-line.png'),
  dreptunghi1: require('../assets/Images/Rectangle13.png'),
  dreptunghi1: require('../assets/Images/Rectangle12.png'),
  presenting: require('../assets/Images/image14.png'),
  presenting2: require('../assets/Images/image15.png'),
  logo1: require('../assets/Images/image4.png'),
  location: require('../assets/Images/locationicon2.png'),
  logo2: require('../assets/Images/logo2.png'),
  rectangle1: require('../assets/Images/Rectangle1.png'),
  rectangle2: require('../assets/Images/Rectangle2.png'),
  rectangle3: require('../assets/Images/Rectangle3.png'),
  goal: require('../assets/Images/goalsicon.png'),
  mygoalrec: require('../assets/Images/mygoalrect1.png'),
  mygoalrec2: require('../assets/Images/mygoalrec.png'),
  moneybagg: require('../assets/Images/money.png'),
  linemoney: require('../assets/Images/linegoals.png'),

  line2: require('../assets/Images/lineProfile.png'),
  calendar: require('../assets/Images/calendar.png'),
  location2: require('../assets/Images/location2.png'),

  dreptunghi17: require('../assets/Images/Rectangle17.png'),
  dreptunghi20: require('../assets/Images/Rectangle 20.png'),
  dreptunghi21: require('../assets/Images/Rectangle21.png'),
  clopot: require('../assets/Images/clopotel.png'),
  calendar: require('../assets/Images/calendar.png'),
  location2: require('../assets/Images/location2.png'),
  time: require('../assets/Images/timeicon.png'),
  back: require('../assets/Images/sageata.png'),
  set1: require('../assets/Images/rectset.png'),
  set2: require('../assets/Images/rectset1.png'),
  secgo: require('../assets/Images/securitygo.png'),
  forma: require('../assets/Images/formapush.png'),
  circle: require('../assets/Images/circlepush.png'),
  rectsecurity: require('../assets/Images/rectanglesecurity.png'),
  fireworks: require('../assets/Images/fireworks.png'),
  rectcongr: require('../assets/Images/rectcongr.png'),




}